/* Kumaran Crackers - Price List OCT 2026 (130 products). Fields: no, name, cat, rate, optional img ("images/xyz.jpg") */
window.PRODUCTS_DATA = [
 {"no":1,"name":"4” Deluxe Lakshmi","cat":"Sound Crackers","rate":40},
 {"no":2,"name":"4” Lakshmi","cat":"Sound Crackers","rate":30},
 {"no":3,"name":"3 ½” Lakshmi","cat":"Sound Crackers","rate":25},
 {"no":4,"name":"2 ¾” Kuruvi","cat":"Sound Crackers","rate":22},
 {"no":5,"name":"28 Chorsa","cat":"Sound Crackers","rate":32},
 {"no":6,"name":"28 Giant","cat":"Sound Crackers","rate":38},
 {"no":7,"name":"24x250 Deluxe","cat":"Sound Crackers","rate":60},
 {"no":8,"name":"Red Bijili 50 pcs","cat":"Salt & Peppers","rate":25},
 {"no":9,"name":"Red Bijili 100 pcs","cat":"Salt & Peppers","rate":50},
 {"no":10,"name":"Kumaran’s Bijili 100 pcs","cat":"Salt & Peppers","rate":70},
 {"no":11,"name":"1000 Wala FULL","cat":"Garlands","rate":350},
 {"no":12,"name":"2000 Wala FULL","cat":"Garlands","rate":680},
 {"no":13,"name":"5000 Wala FULL","cat":"Garlands","rate":1670},
 {"no":14,"name":"10000 Wala FULL","cat":"Garlands","rate":3320},
 {"no":15,"name":"1000 Wala SHORT","cat":"Garlands","rate":220},
 {"no":16,"name":"2000 Wala SHORT","cat":"Garlands","rate":420},
 {"no":17,"name":"5000 Wala SHORT","cat":"Garlands","rate":1020},
 {"no":18,"name":"10000 Wala SHORT","cat":"Garlands","rate":2020},
 {"no":19,"name":"Bullet Bomb","cat":"Bombs","rate":40},
 {"no":20,"name":"Atom Bomb","cat":"Bombs","rate":55},
 {"no":21,"name":"Hydro Bomb","cat":"Bombs","rate":65},
 {"no":22,"name":"3 Ply Bomb","cat":"Bombs","rate":90},
 {"no":23,"name":"5 Ply Bomb","cat":"Bombs","rate":110},
 {"no":24,"name":"AK – 07 Bomb","cat":"Bombs","rate":55},
 {"no":25,"name":"AK – 27 Bomb","cat":"Bombs","rate":65},
 {"no":26,"name":"AK – 37 Bomb","cat":"Bombs","rate":80},
 {"no":27,"name":"AK – 47 Bomb","cat":"Bombs","rate":110},
 {"no":28,"name":"Paper Bomb – ¼ Kg","cat":"Bombs","rate":60},
 {"no":29,"name":"Paper Bomb – ½ Kg","cat":"Bombs","rate":110},
 {"no":30,"name":"Jee Boom Baa","cat":"Poppers","rate":20},
 {"no":31,"name":"Black Serpant Big","cat":"Poppers","rate":30},
 {"no":32,"name":"Crack Jack Citput","cat":"Poppers","rate":35},
 {"no":33,"name":"Roll Cap","cat":"Poppers","rate":70},
 {"no":34,"name":"Annam","cat":"Matches","rate":100},
 {"no":35,"name":"Royal","cat":"Matches","rate":120},
 {"no":36,"name":"Hero","cat":"Matches","rate":180},
 {"no":37,"name":"Crown","cat":"Matches","rate":220},
 {"no":38,"name":"Mejasty","cat":"Matches","rate":260},
 {"no":39,"name":"F. Pots Big","cat":"Flower Pots","rate":70},
 {"no":40,"name":"F. Pots Special","cat":"Flower Pots","rate":90},
 {"no":41,"name":"F. Pots Ashoka","cat":"Flower Pots","rate":110},
 {"no":42,"name":"F. Pots Special Kumaran’s","cat":"Flower Pots","rate":135},
 {"no":43,"name":"F. Pots Deluxe 5 Pcs","cat":"Flower Pots","rate":200},
 {"no":44,"name":"Colour Koti","cat":"Flower Pots","rate":220},
 {"no":45,"name":"Tricolor Pots","cat":"Flower Pots","rate":320},
 {"no":46,"name":"Chakkar Big 10 Pcs","cat":"Firing Wheels","rate":40},
 {"no":47,"name":"Chakkar Special","cat":"Firing Wheels","rate":80},
 {"no":48,"name":"Chakkar Deluxe","cat":"Firing Wheels","rate":120},
 {"no":49,"name":"Chakkar Special Magic","cat":"Firing Wheels","rate":90},
 {"no":50,"name":"Chakkar Deluxe Nano","cat":"Firing Wheels","rate":130},
 {"no":51,"name":"Chakkar Mega Cheeto","cat":"Firing Wheels","rate":220},
 {"no":52,"name":"1 ½” Twinkling Star","cat":"Sticks & Threads","rate":35},
 {"no":53,"name":"4” Twinkling Star","cat":"Sticks & Threads","rate":70},
 {"no":54,"name":"7” Pencil Big","cat":"Sticks & Threads","rate":30},
 {"no":55,"name":"Kumaran’s SPL Pencil","cat":"Sticks & Threads","rate":60},
 {"no":56,"name":"12” Pencil Deluxe","cat":"Sticks & Threads","rate":90},
 {"no":57,"name":"Rainbow Color Smoke","cat":"Sticks & Threads","rate":180},
 {"no":58,"name":"Baby Rocket","cat":"Sky Divers","rate":50},
 {"no":59,"name":"Rocket Bomb","cat":"Sky Divers","rate":90},
 {"no":60,"name":"Lunik Rocket","cat":"Sky Divers","rate":110},
 {"no":61,"name":"Jumbo Jet Rocket","cat":"Sky Divers","rate":150},
 {"no":62,"name":"Whistling Rocket","cat":"Sky Divers","rate":200},
 {"no":63,"name":"4 X 4 Wheel","cat":"Rocking Fountain","rate":180},
 {"no":64,"name":"3” Tin Fountain","cat":"Rocking Fountain","rate":110},
 {"no":65,"name":"5” Aqua Water Fount.","cat":"Rocking Fountain","rate":160},
 {"no":66,"name":"Dora Singer","cat":"Rocking Fountain","rate":160},
 {"no":67,"name":"I Cone Coolers","cat":"Rocking Fountain","rate":240},
 {"no":68,"name":"Magical Peacock","cat":"Rocking Fountain","rate":220},
 {"no":69,"name":"Badda Peacock Big","cat":"Rocking Fountain","rate":320},
 {"no":70,"name":"Disco Wheel","cat":"Rocking Fountain","rate":160},
 {"no":71,"name":"Helicopter","cat":"Rocking Fountain","rate":110},
 {"no":72,"name":"Peacock Fountain","cat":"Rocking Fountain","rate":130},
 {"no":73,"name":"TWEET 6000","cat":"Rocking Fountain","rate":150},
 {"no":74,"name":"Dancing Butterfly","cat":"Rocking Fountain","rate":130},
 {"no":75,"name":"Music Siren Big","cat":"Rocking Fountain","rate":240},
 {"no":76,"name":"Fountain 5 in 1","cat":"Rocking Fountain","rate":180},
 {"no":77,"name":"Emu Egg 2 Pcs","cat":"Rocking Fountain","rate":240},
 {"no":78,"name":"1 ½” Chotta Comet","cat":"Night Aerials","rate":60},
 {"no":79,"name":"2” Comet 3 in 1","cat":"Night Aerials","rate":270},
 {"no":80,"name":"2” Pipe Single","cat":"Night Aerials","rate":150},
 {"no":81,"name":"3” Pipe Single","cat":"Night Aerials","rate":270},
 {"no":82,"name":"4” Pipe Single","cat":"Night Aerials","rate":360},
 {"no":83,"name":"3” Fancy 2 Pcs","cat":"Night Aerials","rate":480},
 {"no":84,"name":"4” Fancy 2 Pcs","cat":"Night Aerials","rate":620},
 {"no":85,"name":"3 ½” Pipe 12 Steps","cat":"SPL Sky Fancy","rate":380},
 {"no":86,"name":"4 ½” Pipe Double Ball","cat":"SPL Sky Fancy","rate":470},
 {"no":87,"name":"5” Comet SPL Colours","cat":"SPL Sky Fancy","rate":670},
 {"no":88,"name":"Shooter Heaven Hand","cat":"SPL Sky Fancy","rate":400},
 {"no":89,"name":"Air Gun 7 Bullets","cat":"SPL Sky Fancy","rate":370},
 {"no":90,"name":"30 Peacock Shots","cat":"SPL Sky Fancy","rate":470},
 {"no":91,"name":"60 Peacock Shots","cat":"SPL Sky Fancy","rate":870},
 {"no":92,"name":"5 X 10 Dragon Mines","cat":"SPL Sky Fancy","rate":2220},
 {"no":93,"name":"10 X 10 Sizzling shot","cat":"SPL Sky Fancy","rate":2820},
 {"no":94,"name":"10 X 10 Tail Light Shot","cat":"SPL Sky Fancy","rate":3320},
 {"no":95,"name":"10 X 10 Thunder Shot","cat":"SPL Sky Fancy","rate":3720},
 {"no":96,"name":"7 Shot Colour","cat":"Sky Shots","rate":130},
 {"no":97,"name":"12 Shot Multicolour","cat":"Sky Shots","rate":200},
 {"no":98,"name":"15 Shot Multicolour","cat":"Sky Shots","rate":260},
 {"no":99,"name":"25 Shot Multicolour","cat":"Sky Shots","rate":320},
 {"no":100,"name":"30 Shot Multicolour","cat":"Sky Shots","rate":470},
 {"no":101,"name":"60 Shot Multicolour","cat":"Sky Shots","rate":870},
 {"no":102,"name":"120 Shot Multicolour","cat":"Sky Shots","rate":1670},
 {"no":103,"name":"240 Shot Multicolour","cat":"Sky Shots","rate":3170},
 {"no":104,"name":"Teen’s 15 Items","cat":"Gift Boxes","rate":370},
 {"no":105,"name":"Special 20 Items","cat":"Gift Boxes","rate":470},
 {"no":106,"name":"Super Deluxe 30 Items","cat":"Gift Boxes","rate":870},
 {"no":107,"name":"7 Cm Electric","cat":"Sparklers","rate":20},
 {"no":108,"name":"7 Cm Colour","cat":"Sparklers","rate":21},
 {"no":109,"name":"7 Cm Green","cat":"Sparklers","rate":22},
 {"no":110,"name":"7 Cm Red","cat":"Sparklers","rate":23},
 {"no":111,"name":"10 Cm Electric","cat":"Sparklers","rate":28},
 {"no":112,"name":"10 Cm Colour","cat":"Sparklers","rate":29},
 {"no":113,"name":"10 Cm Green","cat":"Sparklers","rate":30},
 {"no":114,"name":"10 Cm Red","cat":"Sparklers","rate":31},
 {"no":115,"name":"10 Cm Silver Drops","cat":"Sparklers","rate":32},
 {"no":116,"name":"12 Cm Electric","cat":"Sparklers","rate":35},
 {"no":117,"name":"12 Cm Colour","cat":"Sparklers","rate":36},
 {"no":118,"name":"12 Cm Green","cat":"Sparklers","rate":37},
 {"no":119,"name":"12 Cm Red","cat":"Sparklers","rate":38},
 {"no":120,"name":"12 Cm Silver Drops","cat":"Sparklers","rate":39},
 {"no":121,"name":"15 Cm Electric","cat":"Sparklers","rate":50},
 {"no":122,"name":"15 Cm Colour","cat":"Sparklers","rate":51},
 {"no":123,"name":"15 Cm Green","cat":"Sparklers","rate":52},
 {"no":124,"name":"15 Cm Red","cat":"Sparklers","rate":53},
 {"no":125,"name":"30 Cm Electric","cat":"Sparklers","rate":50},
 {"no":126,"name":"30 Cm Colour","cat":"Sparklers","rate":51},
 {"no":127,"name":"30 Cm Green","cat":"Sparklers","rate":52},
 {"no":128,"name":"30 Cm Red","cat":"Sparklers","rate":53},
 {"no":129,"name":"50 Cm Electric","cat":"Sparklers","rate":210},
 {"no":130,"name":"50 Cm Multi Mix","cat":"Sparklers","rate":240}
];
window.POPULAR_DATA = [1, 11, 20, 39, 46, 58, 104, 107];
